use std::{fs, path::PathBuf};

use anyhow::{bail, Context, Result};
use pumpfun_sdk_idl::{idl::Idl, util::anchor_global_discriminator};

fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn rust_type(idl_ty: &str) -> Result<&'static str> {
    match idl_ty {
        "string" => Ok("String"),
        "bool" => Ok("bool"),
        "u64" => Ok("u64"),
        other => bail!("unsupported idl arg type: {other}"),
    }
}

fn main() -> Result<()> {
    // Usage:
    // cargo run -p idl-gen -- <idl_json_path> <out_rs_path>
    let mut args = std::env::args().skip(1);
    let in_path: PathBuf = args
        .next()
        .map(PathBuf::from)
        .context("missing <idl_json_path>")?;
    let out_path: PathBuf = args
        .next()
        .map(PathBuf::from)
        .context("missing <out_rs_path>")?;

    let json = fs::read_to_string(&in_path).with_context(|| format!("read {:?}", in_path))?;
    let idl: Idl = serde_json::from_str(&json).context("parse idl json")?;

    // Generate one Rust module per instruction.
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by tools/idl-gen. DO NOT EDIT BY HAND.\n\n");

    for ix in &idl.instructions {
        let ix_mod = to_snake_case(&ix.name);

        // discriminator for anchor global ix
        let disc = anchor_global_discriminator(&ix.name);
        let disc_list = disc
            .iter()
            .map(|b| b.to_string())
            .collect::<Vec<_>>()
            .join(", ");

        // Accounts struct
        let mut accounts_fields = String::new();
        let mut metas_list = String::new();

        for a in &ix.accounts {
            let field = to_snake_case(&a.name);
            accounts_fields.push_str(&format!("        pub {field}: Pubkey,\n"));

            // meta selection
            let meta = if a.is_signer && a.is_mut {
                format!("            AccountMeta::new(a.{field}, true),\n")
            } else if a.is_signer && !a.is_mut {
                format!("            AccountMeta::new_readonly(a.{field}, true),\n")
            } else if !a.is_signer && a.is_mut {
                format!("            AccountMeta::new(a.{field}, false),\n")
            } else {
                format!("            AccountMeta::new_readonly(a.{field}, false),\n")
            };
            metas_list.push_str(&meta);
        }

        // Args struct
        let mut args_fields = String::new();
        for arg in &ix.args {
            let field = to_snake_case(&arg.name);
            let ty = rust_type(&arg.ty)?;
            args_fields.push_str(&format!("        pub {field}: {ty},\n"));
        }

        out.push_str(&format!(
            r#"
pub mod {ix_mod} {{
    use borsh::{{BorshDeserialize, BorshSerialize}};
    use solana_sdk::{{
        instruction::{{AccountMeta, Instruction}},
        pubkey::Pubkey,
    }};

    /// Anchor discriminator for `global:{ix_name}`
    pub const DISCRIMINATOR: [u8; 8] = [{disc_list}];

    #[derive(Debug, Clone, BorshSerialize, BorshDeserialize)]
    pub struct Args {{
{args_fields}    }}

    #[derive(Debug, Clone, Copy)]
    pub struct Accounts {{
{accounts_fields}    }}

    pub fn build_ix(program_id: Pubkey, a: Accounts, args: Args) -> Instruction {{
        let mut data = Vec::with_capacity(8 + 128);
        data.extend_from_slice(&DISCRIMINATOR);
        data.extend_from_slice(&args.try_to_vec().expect("borsh serialize"));

        let accounts = vec![
{metas_list}        ];

        Instruction {{
            program_id,
            accounts,
            data,
        }}
    }}
}}
"#,
            ix_mod = ix_mod,
            ix_name = ix.name,
            disc_list = disc_list,
            accounts_fields = accounts_fields,
            metas_list = metas_list,
            args_fields = args_fields,
        ));
    }

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("mkdir {:?}", parent))?;
    }
    fs::write(&out_path, out).with_context(|| format!("write {:?}", out_path))?;

    eprintln!("generated {:?}", out_path);
    Ok(())
}
