use std::{fs, path::PathBuf};

use anyhow::{bail, Context, Result};
use pumpfun_sdk_idl::{idl::Idl, util::anchor_global_discriminator};

fn main() -> Result<()> {
    // Usage:
    // cargo run -p idl-gen -- <idl_json_path> <out_rs_path>
    let mut args = std::env::args().skip(1);
    let in_path: PathBuf = args
        .next()
        .map(PathBuf::from)
        .context("missing <idl_json_path>")?;
    let out_path: PathBuf = args
        .next()
        .map(PathBuf::from)
        .context("missing <out_rs_path>")?;

    let json = fs::read_to_string(&in_path).with_context(|| format!("read {:?}", in_path))?;
    let idl: Idl = serde_json::from_str(&json).context("parse idl json")?;

    // For milestone 2 we generate only what we need: create_v2 module
    let create_v2 = idl
        .instructions
        .iter()
        .find(|ix| ix.name == "create_v2")
        .context("IDL does not contain instruction 'create_v2'")?;

    // Validate arg types we support in this generator
    for a in &create_v2.args {
        if a.ty != "string" && a.ty != "bool" {
            bail!("unsupported arg type '{}' for arg '{}'", a.ty, a.name);
        }
    }

    let disc = anchor_global_discriminator("create_v2");
    let disc_list = disc
        .iter()
        .map(|b| b.to_string())
        .collect::<Vec<_>>()
        .join(", ");

    let out = format!(
        r#"// AUTO-GENERATED by tools/idl-gen. DO NOT EDIT BY HAND.

pub mod create_v2 {{
    use borsh::{{BorshDeserialize, BorshSerialize}};
    use solana_sdk::{{
        instruction::{{AccountMeta, Instruction}},
        pubkey::Pubkey,
    }};

    /// Anchor discriminator for `global:create_v2`
    pub const DISCRIMINATOR: [u8; 8] = [{disc_list}];

    #[derive(Debug, Clone, BorshSerialize, BorshDeserialize)]
    pub struct Args {{
        pub name: String,
        pub symbol: String,
        pub uri: String,
        pub is_mayhem_mode: bool,
    }}

    #[derive(Debug, Clone, Copy)]
    pub struct Accounts {{
        pub mint: Pubkey,
        pub mint_authority: Pubkey,
        pub bonding_curve: Pubkey,
        pub associated_bonding_curve_token_account: Pubkey,
        pub global: Pubkey,
        pub user: Pubkey,
        pub system_program: Pubkey,
        pub token_program: Pubkey,
        pub associated_token_program: Pubkey,
        pub mayhem_program: Pubkey,
        pub global_params: Pubkey,
        pub sol_vault: Pubkey,
        pub mayhem_state: Pubkey,
        pub mayhem_token_vault: Pubkey,
    }}

    pub fn build_ix(program_id: Pubkey, a: Accounts, args: Args) -> Instruction {{
        let mut data = Vec::with_capacity(8 + 128);
        data.extend_from_slice(&DISCRIMINATOR);
        data.extend_from_slice(&args.try_to_vec().expect("borsh serialize"));

        let accounts = vec![
            AccountMeta::new(a.mint, true),
            AccountMeta::new_readonly(a.mint_authority, false),
            AccountMeta::new(a.bonding_curve, false),
            AccountMeta::new(a.associated_bonding_curve_token_account, false),
            AccountMeta::new(a.global, false),
            AccountMeta::new(a.user, true),
            AccountMeta::new_readonly(a.system_program, false),
            AccountMeta::new_readonly(a.token_program, false),
            AccountMeta::new_readonly(a.associated_token_program, false),
            AccountMeta::new_readonly(a.mayhem_program, false),
            AccountMeta::new_readonly(a.global_params, false),
            AccountMeta::new(a.sol_vault, false),
            AccountMeta::new(a.mayhem_state, false),
            AccountMeta::new(a.mayhem_token_vault, false),
        ];

        Instruction {{
            program_id,
            accounts,
            data,
        }}
    }}
}}
"#
    );

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("mkdir {:?}", parent))?;
    }
    fs::write(&out_path, out).with_context(|| format!("write {:?}", out_path))?;

    eprintln!("generated {:?}", out_path);
    Ok(())
}
